const {chromium}=require('playwright');const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
(async()=>{
 const {PGlite}=await import('@electric-sql/pglite'),{pg_trgm}=await import('@electric-sql/pglite/contrib/pg_trgm'),{fuzzystrmatch}=await import('@electric-sql/pglite/contrib/fuzzystrmatch');
 const db=new PGlite({extensions:{pg_trgm,fuzzystrmatch}});const admin='35eadffb-84a8-499c-8a24-bdb0231ef2de';
 await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,raw_user_meta_data jsonb DEFAULT '{}',created_at timestamptz DEFAULT now());CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;GRANT USAGE ON SCHEMA auth TO authenticated;GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated;INSERT INTO auth.users(id,email) VALUES('${admin}','admin@example.invalid');CREATE SCHEMA storage;CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);CREATE TABLE storage.objects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),bucket_id text,name text);ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;GRANT USAGE ON SCHEMA storage TO authenticated;GRANT SELECT,INSERT,DELETE ON storage.objects TO authenticated;`);
 await db.exec(fs.readFileSync('sql/v4/01_INSTALAR_ATUALIZACAO_V4.sql','utf8'));await db.exec(fs.readFileSync('sql/v4/02_PDFS_PRIVADOS.sql','utf8'));
 const accounts=new Map([['admin@example.invalid',admin]]);let queue=Promise.resolve();const serial=fn=>{const job=queue.then(fn);queue=job.catch(()=>{});return job;};
 fs.mkdirSync('qa/v4',{recursive:true});
 const browser=await chromium.launch({executablePath:process.env.FGPT_CHROMIUM||'/tmp/fgpt-v4-browser/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--disable-gpu'],env:{...process.env,LD_LIBRARY_PATH:'/tmp/fgpt-v4-browser',FONTCONFIG_PATH:'/etc/fonts'}});
 const errors=[];let activePage;
 try{
 const setup=async(width)=>{const context=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'});const page=await context.newPage();page.setDefaultTimeout(12000);activePage=page;page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await context.addInitScript(()=>localStorage.setItem('fgpt-supabase-v1',JSON.stringify({url:'https://fgpt-test.supabase.co',key:'sb_publishable_test',table:'vw_fgpt_acervo_v3',rpc:'buscar_fgpt_v3',queryParam:'p_busca',limitParam:'p_limite',orderColumn:'id'})));
 await page.route('https://fgpt.test/**',async route=>{const name=new URL(route.request().url()).pathname;const rel=name==='/'?'index.html':decodeURIComponent(name.slice(1));const file=path.resolve('public',rel);assert.ok(file.startsWith(path.resolve('public')+path.sep));const mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp','.woff2':'font/woff2','.svg':'image/svg+xml'};if(!fs.existsSync(file))return route.fulfill({status:404,body:'Not found'});return route.fulfill({status:200,contentType:mime[path.extname(file)]||'application/octet-stream',body:fs.readFileSync(file)});});
 await page.route('https://fgpt-test.supabase.co/**',route=>serial(async()=>{
 const req=route.request(),u=new URL(req.url());const reply=(body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
 try{
 if(u.pathname==='/auth/v1/token'){const d=req.postDataJSON();const id=d.refresh_token?.slice(8)||accounts.get(d.email);if(!id)return reply({message:'invalid login'},400);return reply({access_token:'access:'+id,refresh_token:'refresh:'+id,expires_in:3600});}
 if(u.pathname==='/auth/v1/signup'){assert.equal(u.searchParams.get('redirect_to'),'https://fgpt.test/');const d=req.postDataJSON(),id=crypto.randomUUID();await db.exec('RESET ROLE');await db.query('INSERT INTO auth.users(id,email,raw_user_meta_data) VALUES($1,$2,$3)',[id,d.email,d.data]);accounts.set(d.email,id);return reply({user:{id}});}
 if(u.pathname==='/auth/v1/logout')return reply({});
 const token=req.headers().authorization||'';const id=token.replace('Bearer access:','');if(!/^[a-f0-9-]{36}$/.test(id))return reply({},401);
 await db.exec('RESET ROLE; SET ROLE authenticated;');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[id]);
 if(u.pathname==='/rest/v1/vw_fgpt_acervo_v3')return reply((await db.query('SELECT * FROM public.vw_fgpt_acervo_v3 ORDER BY id LIMIT 500 OFFSET $1',[Number(u.searchParams.get('offset')||0)])).rows);
 if(u.pathname.startsWith('/rest/v1/rpc/')){const name=u.pathname.split('/').at(-1),args=req.postDataJSON()||{};assert.match(name,/^[a-z0-9_]+$/);const keys=Object.keys(args);keys.forEach(k=>assert.match(k,/^[a-z0-9_]+$/));const params=keys.map((k,i)=>k+'=> $'+(i+1)).join(',');const setOf=['buscar_fgpt_v3','relacionados_fgpt_v3','fgpt_anexos_v4'].includes(name);const res=await db.query(setOf?`SELECT to_jsonb(x) result FROM public.${name}(${params}) x`:`SELECT public.${name}(${params}) result`,keys.map(k=>args[k]));const value=res.rows[0]?.result;return reply(setOf?res.rows.map(r=>r.result):value);}
 if(u.pathname.startsWith('/storage/v1/object/sign/')){const object=u.pathname.split('/falhas-gpt-procedimentos/')[1];const r=await db.query('SELECT * FROM storage.objects WHERE name=$1',[object]);if(!r.rows.length)return reply({},403);return reply({signedURL:'/object/sign/falhas-gpt-procedimentos/'+object+'?token=test'});}
 if(u.pathname.startsWith('/storage/v1/object/falhas-gpt-procedimentos/')){const object=u.pathname.split('/falhas-gpt-procedimentos/')[1];await db.query('INSERT INTO storage.objects(bucket_id,name) VALUES($1,$2)',['falhas-gpt-procedimentos',object]);return reply({Key:object});}
 throw new Error('Unexpected endpoint '+u.pathname);
 }catch(e){return reply({code:e.code||'P0001',message:e.message},e.code==='42501'?403:400);}
 }));await page.goto('https://fgpt.test/');await page.locator('#auth-form').waitFor();return {page,context};};
 const login=async(page,email)=>{await page.locator('#auth-form [name=email]').fill(email);await page.locator('#auth-form [name=password]').fill('test-password-123');await page.locator('#auth-form button[type=submit]').click();await page.locator('.sidebar').waitFor();};
 let {page,context}=await setup(1440);await page.screenshot({path:'qa/v4/login-desktop.png'});await page.emulateMedia({reducedMotion:'no-preference'});const positions=await page.evaluate(async()=>{const seen=new Set(),end=performance.now()+1600;while(performance.now()<end){seen.add(getComputedStyle(document.querySelector('.charleia-frame')).backgroundPositionX);await new Promise(requestAnimationFrame);}return [...seen];});assert.ok(positions.length>=3,'Mascot must animate through frames');await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.charleia-frame').first().evaluate(el=>getComputedStyle(el).animationName),'none');await login(page,'admin@example.invalid');
 await page.getByRole('button',{name:'Administração',exact:true}).click();await page.getByRole('button',{name:'Novo procedimento',exact:true}).waitFor();
 await page.getByRole('tab',{name:'Liberação de RE'}).click();await page.getByRole('textbox',{name:'RE para liberar'}).fill('59-00001');await page.getByRole('button',{name:'Liberar RE',exact:true}).click();await page.getByText('59-00001',{exact:true}).waitFor();
 await page.locator('[data-admin-file=res]').setInputFiles('tests/fixtures/import-res.xlsx');await page.getByRole('button',{name:'Liberar 2 RE(s)',exact:true}).waitFor();assert.ok((await page.locator('.import-preview').innerText()).includes('2 RE(s) único(s)'));assert.ok(!(await page.locator('.import-preview').innerText()).includes('Nome ignorado'));await page.getByRole('button',{name:'Liberar 2 RE(s)',exact:true}).click();await page.getByText('59-00003',{exact:true}).waitFor();await page.screenshot({path:'qa/v4/admin-res-desktop.png',fullPage:true});
 await page.getByRole('tab',{name:'Procedimentos',exact:true}).click();await page.getByRole('button',{name:'Novo procedimento',exact:true}).click();
 await page.locator('[data-admin-file=single-pdf]').setInputFiles('tests/fixtures/procedimento-teste.pdf');await page.getByText('Texto extraído. Revise a ordem dos passos e preencha o resumo antes de disponibilizar.',{exact:true}).waitFor();
 assert.match(await page.locator('[name=procedimento_completo]').inputValue(),/Segunda pagina/);
 const fields={topico:'Porta não abre — documento de teste',categoria:'Portas',serie:'7000',numero_documento:'TESTE-01',revisao:'01',resumo:'Resumo apenas para validação da interface.',fonte:'Documento fictício de QA',aliases:'porta travada na abertura',palavras_chave:'porta\nabertura'};
 for(const [name,value] of Object.entries(fields))await page.locator('#admin-procedure-form [name='+name+']').fill(value);
 await page.locator('[name=publicado]').check();await page.locator('[name=revisado]').check();await page.getByRole('button',{name:'Salvar procedimento',exact:true}).click();await page.getByText(/Procedimento criado: trafego-trens-falhasgptapp-01/).waitFor();
 assert.equal(await page.locator('[name=resumo]').inputValue(),fields.resumo);await page.screenshot({path:'qa/v4/admin-editor-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Voltar',exact:true}).click();await page.locator('[data-admin-file=batch-pdf]').setInputFiles('tests/fixtures/procedimento-teste.pdf');await page.getByRole('button',{name:'Criar 1 rascunho(s)',exact:true}).waitFor();await page.getByRole('button',{name:'Criar 1 rascunho(s)',exact:true}).click();await page.getByText(/1 PDF\(s\) importado\(s\) como rascunho/).waitFor();assert.equal(await page.getByText('Rascunho',{exact:true}).count(),1);
 await page.getByRole('button',{name:'Sair',exact:true}).click();await page.getByRole('button',{name:'Cadastrar',exact:true}).click();
 await page.locator('#auth-form [name=nome]').fill('Operador QA');await page.locator('#auth-form [name=re]').fill('59-99999');await page.locator('#auth-form [name=email]').fill('operator@example.invalid');await page.locator('#auth-form [name=password]').fill('test-password-123');await page.getByRole('button',{name:'Criar conta',exact:true}).click();await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').innerText(),/Cadastro não concluído/);
 await page.locator('#auth-form [name=nome]').fill('Operador QA');await page.locator('#auth-form [name=re]').fill('59-00002');await page.locator('#auth-form [name=email]').fill('operator@example.invalid');await page.locator('#auth-form [name=password]').fill('test-password-123');await page.getByRole('button',{name:'Criar conta',exact:true}).click();await page.getByText(/Se o cadastro foi aceito/).waitFor();await login(page,'operator@example.invalid');
 assert.equal(await page.getByRole('button',{name:'Administração',exact:true}).count(),0);await page.locator('#chat-input').fill(fields.topico);await page.locator('#chat-input').press('Enter');await page.locator('.procedure-card h3').first().waitFor();assert.equal(await page.locator('.procedure-card h3').first().innerText(),fields.topico);assert.equal(await page.locator('.charleia[data-state=cheerful]').count(),1);await page.getByRole('button',{name:'Ver resumo',exact:true}).click();await page.getByRole('button',{name:'procedimento-teste.pdf',exact:true}).waitFor();await page.getByRole('button',{name:'Ver procedimento completo',exact:true}).click();assert.match(await page.locator('#procedure-panel').innerText(),/Segunda pagina/);await page.getByRole('button',{name:'Sim, encontrei',exact:true}).click();assert.ok(await page.locator('.charleia[data-state=success]').count()>0);await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Nova consulta',exact:true}).click();await page.locator('#chat-input').fill('zzzz999999');await page.locator('#chat-input').press('Enter');await page.getByRole('heading',{name:'Nenhum procedimento encontrado'}).waitFor();assert.equal(await page.locator('.charleia[data-state=sad]').count(),1);
 await serial(async()=>{await db.exec('RESET ROLE;SET ROLE authenticated');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[admin]);await db.query("SELECT public.fgpt_admin_alterar_re_v4('59-00002',false)");});await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await page.getByRole('heading',{name:'Liberar acesso',exact:true}).waitFor();assert.equal(await page.locator('.procedure-card').count(),0);assert.deepEqual(errors,[]);await context.close();
 ({page,context}=await setup(390));await page.screenshot({path:'qa/v4/login-mobile.png',fullPage:true});await login(page,'admin@example.invalid');await page.getByRole('button',{name:'Abrir menu'}).click();await page.getByRole('button',{name:'Administração',exact:true}).click();await page.getByRole('button',{name:'Novo procedimento',exact:true}).waitFor();
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow at '+width);}
 await page.setViewportSize({width:390,height:900});await page.screenshot({path:'qa/v4/admin-procedures-mobile.png',fullPage:true});await page.getByRole('tab',{name:'Liberação de RE'}).click();await page.getByText('59-00001',{exact:true}).waitFor();await page.screenshot({path:'qa/v4/admin-res-mobile.png',fullPage:true});const action=await page.locator('[data-admin=toggle-re]').first().boundingBox();assert.ok(action.x>=0&&action.x+action.width<=390,'RE action must fit mobile viewport');
 assert.deepEqual(errors,[]);await context.close();console.log('PASS browser V4: actual SQL RPCs behind simulated Auth/Storage HTTP; admin login, single RE and Excel preview/import, PDF extraction/upload, official procedure, draft batch import, rejected/accepted signup, operator permissions, ranked search, summary/full/PDF, mascot states, revoked active session, four responsive widths.');
 }catch(e){console.error('UI alert:',await activePage?.locator('[role=alert]').allTextContents());await activePage?.screenshot({path:'qa/v4/failure.png',fullPage:true}).catch(()=>{});throw e;}finally{await browser.close();await db.close();}
})().catch(e=>{console.error({message:e.message,stack:e.stack?.split('\n').slice(0,6).join('\n')});process.exit(1)});
