import {PGlite} from '@electric-sql/pglite';
import {pg_trgm} from '@electric-sql/pglite/contrib/pg_trgm';
import {fuzzystrmatch} from '@electric-sql/pglite/contrib/fuzzystrmatch';
import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const db=new PGlite({extensions:{pg_trgm,fuzzystrmatch}});
const admin='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',operator='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,raw_user_meta_data jsonb DEFAULT '{}',created_at timestamptz DEFAULT now());
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
GRANT USAGE ON SCHEMA auth TO authenticated,anon;GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated,anon;
CREATE SCHEMA storage;CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
CREATE TABLE storage.objects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),bucket_id text,name text);
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;GRANT USAGE ON SCHEMA storage TO authenticated,anon;
GRANT SELECT,INSERT,UPDATE,DELETE ON storage.objects TO authenticated,anon;
INSERT INTO auth.users(id,email) VALUES('${admin}','admin-new@example.invalid');`);
const raw=await fs.readFile('sql/instalacao/01_INSTALAR_COMPLETO_V5.sql','utf8');
await assert.rejects(db.exec(raw),/Preencha o UUID/);await db.exec('ROLLBACK');
assert.equal((await db.query("SELECT to_regnamespace('falhas_gpt') n")).rows[0].n,null);
await assert.rejects(db.exec(raw.replace('COLE_UUID_ADMIN_AQUI\';',operator+"';")),/Administrador não encontrado/);await db.exec('ROLLBACK');
const install=raw.replace("'COLE_UUID_ADMIN_AQUI'","'"+admin+"'");await db.exec(install);
const validation=await db.exec(await fs.readFile('sql/instalacao/02_VALIDAR_INSTALACAO_COMPLETA.sql','utf8'));
assert.equal(validation.at(-1).rows[0].instalacao_basica_ok,true);
assert.deepEqual((await db.query('SELECT usuario_id FROM falhas_gpt.administradores')).rows,[{usuario_id:admin}]);
await db.exec('SET ROLE authenticated');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[admin]);
assert.equal((await db.query('SELECT public.fgpt_sessao_v4() v')).rows[0].v.admin,true);
await db.query('SELECT public.fgpt_admin_liberar_res_v4($1) AS v',[['59-12345']]);
const item={topico:'Documento novo de teste',tipo:'procedimento',categoria:'Teste',serie:'7000',resumo:'Resumo fictício',procedimento_completo:'Existe aqui um transdutor auxiliar exclusivo.',fonte:'QA',revisao:'1',publicado:true};
const procedure=(await db.query('SELECT public.fgpt_admin_salvar_procedimento_v4($1) v',[item])).rows[0].v;
assert.match(procedure.codigo,/-01$/);
await db.exec('RESET ROLE');
await db.query('INSERT INTO auth.users(id,email,raw_user_meta_data) VALUES($1,$2,$3)',[operator,'operator@example.invalid',{app:'falhas_gpt',nome:'Operador QA',re:'59-12345'}]);
await db.exec('SET ROLE authenticated');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[operator]);
assert.equal((await db.query('SELECT public.fgpt_sessao_v4() v')).rows[0].v.admin,false);
assert.equal((await db.query("SELECT id FROM public.buscar_fgpt_v3('transdutor auxiliar')")).rows[0].id,procedure.id);
await assert.rejects(db.query('SELECT public.fgpt_admin_excluir_procedimento_v5($1,$2)',[procedure.id,1]),/exclusivo/);
await db.exec('RESET ROLE');
await assert.rejects(db.exec(install),/Já existe um acervo/);await db.exec('ROLLBACK');
assert.equal((await db.query('SELECT count(*)::int n FROM falhas_gpt.procedimentos')).rows[0].n,1);
await db.exec(await fs.readFile('sql/v5/04_ATUALIZAR_V4_PARA_V5.sql','utf8'));
assert.equal((await db.query('SELECT count(*)::int n FROM falhas_gpt.perfis')).rows[0].n,1);
assert.equal((await db.query('SELECT count(*)::int n FROM falhas_gpt.procedimentos')).rows[0].n,1);
await db.exec('SET ROLE anon');await assert.rejects(db.query("SELECT * FROM public.buscar_fgpt_v3('transdutor')"),/permission denied/);
await db.close();
console.log('PASS instalação completa: UUID configurável, pré-validação, criação do zero, admin/RE, busca, proteção contra reinstalação sobre dados e atualização preservada.');
