process.on('uncaughtException',e=>{console.error({message:e.message,code:e.code,where:e.where,position:e.position,stack:e.stack?.split('\n').slice(0,4).join('\n')});process.exit(1)});
import {PGlite} from '@electric-sql/pglite';
import {pg_trgm} from '@electric-sql/pglite/contrib/pg_trgm';
import {fuzzystrmatch} from '@electric-sql/pglite/contrib/fuzzystrmatch';
import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const db=new PGlite({extensions:{pg_trgm,fuzzystrmatch}});
const admin='35eadffb-84a8-499c-8a24-bdb0231ef2de',operator='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role; CREATE SCHEMA auth;
CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,raw_user_meta_data jsonb DEFAULT '{}',created_at timestamptz DEFAULT now());
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
GRANT USAGE ON SCHEMA auth TO authenticated,anon; GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated,anon;
CREATE SCHEMA storage;CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
CREATE TABLE storage.objects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),bucket_id text,name text);
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;GRANT USAGE ON SCHEMA storage TO authenticated,anon;GRANT SELECT,INSERT,DELETE,UPDATE ON storage.objects TO authenticated,anon;
CREATE POLICY generic_old_policy ON storage.objects FOR ALL TO authenticated,anon USING(true) WITH CHECK(true);
INSERT INTO auth.users(id,email) VALUES ('${admin}','admin@example.invalid'),('${other}','old@example.invalid');
CREATE FUNCTION public.buscar_fgpt_v2(text,integer) RETURNS text LANGUAGE sql AS $$ SELECT 'preservada'::text $$;`);
await db.exec(await fs.readFile('sql/01_instalar_motor_busca.sql','utf8'));
await db.exec(await fs.readFile('sql/02_exemplos_para_validar.sql','utf8'));
const install=await fs.readFile('sql/v4/01_INSTALAR_ATUALIZACAO_V4.sql','utf8');
await db.exec(install);await db.exec(install);await db.exec(await fs.readFile('sql/v4/02_PDFS_PRIVADOS.sql','utf8'));await db.exec(await fs.readFile('sql/v4/02_PDFS_PRIVADOS.sql','utf8'));
assert.equal((await db.query('SELECT count(*)::int n FROM falhas_gpt.procedimentos')).rows[0].n,4);
assert.equal((await db.query("SELECT public.buscar_fgpt_v2('x',1) v")).rows[0].v,'preservada');
const login=async id=>{await db.exec('RESET ROLE; SET ROLE authenticated;');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[id]);};
const call=async(name,args=[],params='')=>(await db.query(`SELECT public.${name}(${params||args.map((_,i)=>'$'+(i+1)).join(',')}) v`,args)).rows[0].v;
await login(admin);assert.equal((await call('fgpt_sessao_v4')).admin,true);
assert.deepEqual(await call('fgpt_admin_liberar_res_v4',[['5900001','59-00001','59-00002']]),{novos:2,existentes:0,bloqueados_preservados:0});
await assert.rejects(call('fgpt_admin_liberar_res_v4',[['58-00001']]),/inválido/);
await db.exec('RESET ROLE');
const insertUser=async(id,re,app='falhas_gpt')=>db.query('INSERT INTO auth.users(id,email,raw_user_meta_data) VALUES($1,$2,$3)',[id,id+'@example.invalid',{re,app,nome:'Operador teste',admin:true,role:'admin'}]);
await assert.rejects(insertUser('33333333-3333-4333-8333-333333333333','59-99999'),/não autorizado/);
await insertUser(operator,'5900001');await assert.rejects(insertUser('44444444-4444-4444-8444-444444444444','59-00001'),/não autorizado/);
await insertUser('55555555-5555-4555-8555-555555555555','59-99999','outro_app');
await login(operator);const session=await call('fgpt_sessao_v4');assert.equal(session.autorizado,true);assert.equal(session.admin,false);assert.equal(session.re,'59-00001');
for(const [name,args] of [['fgpt_admin_liberar_res_v4',[['59-00003']]],['fgpt_admin_alterar_re_v4',['59-00001',true]],['fgpt_admin_listar_res_v4',[]],['fgpt_admin_salvar_procedimento_v4',[{topico:'Inválido',tipo:'procedimento'}]]])await assert.rejects(call(name,args),/exclusivo/);
await assert.rejects(db.exec('UPDATE falhas_gpt.administradores SET ativo=true'),/permission denied/);
await assert.rejects(db.exec("UPDATE falhas_gpt.res_liberados SET ativo=true"),/permission denied/);
assert.ok((await db.query("SELECT * FROM public.buscar_fgpt_v3('prota nao abre')")).rows[0].topico==='Porta não abre');
await login(admin);await call('fgpt_admin_alterar_re_v4',['59-00001',false]);
const reimport=await call('fgpt_admin_liberar_res_v4',[['59-00001']]);assert.equal(reimport.bloqueados_preservados,1);
await login(operator);assert.equal((await call('fgpt_sessao_v4')).autorizado,false);assert.equal((await db.query('SELECT * FROM public.vw_fgpt_acervo_v3')).rows.length,0);await assert.rejects(call('buscar_fgpt_v3',['porta']),/sem acesso/);
await login(admin);await call('fgpt_admin_alterar_re_v4',['59-00001',true]);
await login(other);assert.equal((await call('fgpt_sessao_v4')).autorizado,false);await call('fgpt_vincular_re_v4',['59-00002','Conta anterior']);assert.equal((await call('fgpt_sessao_v4')).autorizado,true);
await assert.rejects(call('fgpt_vincular_re_v4',['59-00001','Outra tentativa']),/já possui/);
await login(admin);
const input={topico:'Procedimento validado',tipo:'procedimento',publicado:true,categoria:'Portas',serie:'7000',resumo:'Resumo de teste',procedimento_completo:'Conteúdo de teste sem instruções operacionais',fonte:'Manual teste',revisao:'01',aliases:['expressão teste'],palavras_chave:['teste'],relacionados:[]};
await assert.rejects(call('fgpt_admin_salvar_procedimento_v4',[{...input,resumo:''}]),/preencha: resumo/);
const first=await call('fgpt_admin_salvar_procedimento_v4',[input]);assert.equal(first.codigo,'trafego-trens-falhasgptapp-01');
const draft=await call('fgpt_admin_salvar_procedimento_v4',[{topico:'Importado para revisão',tipo:'procedimento',publicado:false}]);assert.equal(draft.codigo,'trafego-trens-falhasgptapp-02');
const updated=await call('fgpt_admin_salvar_procedimento_v4',[{...input,revisao:'02'},first.id,1]);assert.equal(updated.versao_edicao,2);
await assert.rejects(call('fgpt_admin_salvar_procedimento_v4',[input,first.id,1]),/Outro acesso/);
const pdfpath=first.id+'/66666666-6666-4666-8666-666666666666.pdf';
await db.query('INSERT INTO storage.objects(bucket_id,name) VALUES($1,$2)',['falhas-gpt-procedimentos',pdfpath]);
await call('fgpt_admin_anexar_pdf_v4',[first.id,pdfpath,'teste.pdf',500]);
await login(operator);assert.equal((await db.query('SELECT * FROM public.vw_fgpt_acervo_v3 WHERE id=$1',[draft.id])).rows.length,0);assert.equal((await db.query('SELECT * FROM storage.objects')).rows.length,1);
await login(admin);await call('fgpt_admin_alterar_re_v4',['59-00001',false]);await login(operator);assert.equal((await db.query('SELECT * FROM storage.objects')).rows.length,0);
await db.exec('RESET ROLE; SET ROLE anon');await db.query("SELECT set_config('request.jwt.claim.sub','',false)");assert.equal((await db.query('SELECT * FROM storage.objects')).rows.length,0);await assert.rejects(call('fgpt_sessao_v4'),/permission denied/);await assert.rejects(call('fgpt_admin_liberar_res_v4',[['59-00003']]),/permission denied/);
await db.exec('RESET ROLE');await db.exec(install);await login(operator);assert.equal((await db.query('SELECT * FROM storage.objects')).rows.length,0);
await db.exec('RESET ROLE');
// Server-assigned numbering keeps all digits beyond 99.
await db.exec("SELECT setval('falhas_gpt.procedimento_numero_v4',99,true)");await login(admin);const hundred=await call('fgpt_admin_salvar_procedimento_v4',[{topico:'Registro cem',tipo:'procedimento',publicado:false}]);assert.ok(hundred.codigo.endsWith('-100'));
console.log('PASS V4: reinstallation preserves data/V2; admin UUID; signup allowlist; invalid/duplicate RE blocked; metadata cannot grant admin; revoked RE blocks existing JWT and PDF reads; imports preserve revoked REs; existing-user link; operator/anon writes blocked; required fields; numbering; edit conflict; private storage; drafts hidden.');
await db.close();
